<template>
  <AppLayout>
    <div class="w-full max-w-4xl space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-700">
      <!-- Back Navigation -->
      <button @click="goBack"
        class="flex items-center gap-2 text-slate-400 hover:text-[#6366F1] transition-colors font-bold text-[10px] uppercase tracking-widest ubuntu">
        <ArrowLeft class="w-4 h-4" /> Back to Inbox
      </button>

      <!-- Loading State -->
      <div v-if="loading" class="bg-surface/60 border border-white/5 rounded-3xl p-12 text-center">
        <div class="animate-spin w-8 h-8 border-4 border-primary border-t-transparent rounded-full mx-auto"></div>
        <p class="text-slate-400 text-sm mt-4 outfit">Loading notification...</p>
      </div>

      <!-- Error State -->
      <div v-else-if="error" class="bg-surface/60 border border-white/5 rounded-3xl p-12 text-center">
        <AlertCircle class="w-16 h-16 text-red-500 mx-auto mb-4" />
        <h3 class="text-xl font-bold text-white font-headline mb-2">Notification Not Found</h3>
        <p class="text-slate-400 text-sm outfit mb-6">{{ error }}</p>
        <button @click="goBack"
          class="px-6 py-3 bg-primary text-white rounded-xl text-[10px] font-bold uppercase tracking-widest shadow-xl hover:bg-primary/90 transition-all ubuntu">
          Back to Notifications
        </button>
      </div>

      <!-- Notification Detail Card -->
      <div v-else-if="notification"
        class="bg-surface/80 border border-white/5 rounded-3xl overflow-hidden shadow-2xl relative">
        <!-- Glass reflection -->
        <div class="absolute inset-0 bg-gradient-to-br from-white/[0.03] to-transparent pointer-events-none"></div>

        <!-- Header Area -->
        <div class="p-8 md:p-12 border-b border-white/5 relative bg-surface/30">
          <div class="flex flex-col md:flex-row md:items-start justify-between gap-6 mb-8">
            <div class="flex items-start gap-4 md:gap-6">
              <div
                :class="['w-14 h-14 rounded-2xl flex items-center justify-center shrink-0 border shadow-inner mt-1', notification.bgClass]">
                <component :is="getIconComponent(notification.icon)" :class="['w-7 h-7', notification.textClass]" />
              </div>
              <div class="space-y-2">
                <div class="flex flex-wrap items-center gap-3">
                  <h1 class="text-3xl font-bold text-white tracking-tight font-headline">{{ notification.title }}</h1>
                </div>
                <p
                  class="text-[11px] text-slate-500 uppercase tracking-widest font-bold ubuntu flex items-center gap-2">
                  <Calendar class="w-3.5 h-3.5" /> {{ formattedDate }}
                </p>
              </div>
            </div>

            <div class="flex gap-3 shrink-0">
              <button @click="toggleStar"
                :class="['w-10 h-10 rounded-xl bg-surface-container border border-white/5 flex items-center justify-center transition-all shadow-xl group', isStarred ? 'text-amber-400' : 'text-slate-400 hover:text-white hover:bg-surface-container-high']">
                <Star :class="['w-5 h-5', isStarred ? 'fill-amber-400' : 'group-hover:fill-amber-400']" />
              </button>
              <button @click="shareNotification"
                class="w-10 h-10 rounded-xl bg-surface-container border border-white/5 flex items-center justify-center text-slate-400 hover:text-white hover:bg-surface-container-high transition-all shadow-xl">
                <Share2 class="w-5 h-5" />
              </button>
            </div>
          </div>

          <!-- Meta Info Row -->
          <div class="flex flex-wrap items-center gap-6 pt-6 border-t border-white/5">
            <!-- Generated By -->
            <div v-if="notification.data?.sender" class="flex items-center gap-3">
              <img :src="notification.data.sender.avatar || 'https://i.pravatar.cc/150?u=default'"
                :alt="notification.data.sender.name" class="w-8 h-8 rounded-lg border border-white/10 object-cover" />
              <div class="space-y-0.5">
                <p class="text-[10px] text-slate-500 font-bold uppercase tracking-widest ubuntu">Generated By</p>
                <p class="text-sm font-bold text-white outfit">{{ notification.data.sender.name }}</p>
              </div>
            </div>

            <!-- Related Entity -->
            <div v-if="relatedEntity" class="flex items-center gap-3">
              <div
                class="w-8 h-8 rounded-lg bg-surface-container-high border border-white/5 flex items-center justify-center">
                <Folder class="w-4 h-4 text-slate-300" />
              </div>
              <div class="space-y-0.5">
                <p class="text-[10px] text-slate-500 font-bold uppercase tracking-widest ubuntu">Related Entity</p>
                <p class="text-sm font-bold text-white outfit hover:text-primary transition-colors cursor-pointer"
                  @click="navigateToRelated">
                  {{ relatedEntity.name }}
                </p>
              </div>
            </div>

            <!-- Status Change -->
            <div v-if="notification.data?.status_change" class="flex items-center gap-3">
              <div
                class="w-8 h-8 rounded-lg bg-emerald-500/10 border border-emerald-500/20 flex items-center justify-center">
                <Activity class="w-4 h-4 text-emerald-400" />
              </div>
              <div class="space-y-0.5">
                <p class="text-[10px] text-slate-500 font-bold uppercase tracking-widest ubuntu">Status Change</p>
                <p class="text-sm font-bold text-emerald-400 outfit tracking-tight">{{ notification.data.status_change
                  }}</p>
              </div>
            </div>
          </div>
        </div>

        <!-- Body Content Area -->
        <div class="p-8 md:p-12">
          <div class="prose prose-invert prose-slate max-w-none outfit">
            <p class="text-xl text-slate-200 leading-relaxed font-medium mb-6" v-html="formattedMessage"></p>

            <!-- Attachments -->
            <div v-if="notification.data?.attachments?.length" class="mt-10 space-y-4">
              <h4 class="text-sm font-bold text-slate-400 uppercase tracking-widest ubuntu mb-4">Attachments</h4>
              <div v-for="(attachment, index) in notification.data.attachments" :key="index"
                class="bg-surface-container/30 border border-white/5 rounded-2xl p-6 flex flex-col sm:flex-row items-center justify-between gap-6 hover:border-primary/30 transition-colors">
                <div class="flex items-center gap-4">
                  <div
                    :class="['w-12 h-12 rounded-xl flex items-center justify-center border shrink-0', getAttachmentIconClass(attachment.type)]">
                    <component :is="getAttachmentIcon(attachment.type)"
                      :class="['w-6 h-6', getAttachmentTextColor(attachment.type)]" />
                  </div>
                  <div>
                    <h4 class="text-base font-bold text-white outfit mb-1">{{ attachment.name }}</h4>
                    <p class="text-[10px] uppercase font-bold tracking-widest text-slate-500 ubuntu space-font">{{
                      attachment.size }} • {{ attachment.type }}</p>
                  </div>
                </div>
                <button @click="downloadAttachment(attachment)"
                  class="w-full sm:w-auto px-5 py-2 bg-white/5 hover:bg-white/10 text-white text-[10px] font-bold uppercase tracking-widest rounded-xl transition-colors border border-white/10 ubuntu flex items-center gap-2">
                  <Download class="w-3.5 h-3.5" /> Download
                </button>
              </div>
            </div>
          </div>

          <!-- Action Bar -->
          <div class="mt-12 pt-8 border-t border-white/5 flex flex-wrap items-center gap-4">
            <button v-if="relatedEntity?.url" @click="navigateToRelated"
              class="px-8 py-3.5 bg-primary text-white rounded-xl text-[10px] font-bold uppercase tracking-widest shadow-[0_0_20px_rgba(99,102,241,0.2)] hover:shadow-[0_0_30px_rgba(99,102,241,0.3)] transition-all hover:bg-primary/90 ubuntu flex items-center gap-2">
              <ExternalLink class="w-4 h-4" /> View {{ relatedEntity.type }}
            </button>
          </div>
        </div>
      </div>
    </div>
  </AppLayout>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import AppLayout from '@/components/AppLayout.vue'
import {
  ArrowLeft,
  Calendar,
  Star,
  Share2,
  Folder,
  Activity,
  FileText,
  File,
  Image,
  Download,
  ExternalLink,
  MessageSquare,
  Trash2,
  AlertCircle,
  Info,
  CheckCircle2,
  AlertTriangle
} from 'lucide-vue-next'
import { getNotification, markAsRead, deleteNotification as apiDeleteNotification } from '@/services/api'

const router = useRouter()
const route = useRoute()

// State
const loading = ref(true)
const error = ref(null)
const notification = ref(null)
const isStarred = ref(false)
const deleting = ref(false)

// Icon mapping
const iconComponents = {
  Info,
  CheckCircle2,
  AlertCircle,
  AlertTriangle
}

// Computed
const formattedDate = computed(() => {
  if (!notification.value?.created_at) return ''
  const date = new Date(notification.value.created_at)
  return date.toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  })
})

const formattedMessage = computed(() => {
  if (!notification.value?.message) return ''
  // Convert bold markdown to HTML
  return notification.value.message.replace(/\*\*(.*?)\*\*/g, '<strong class="text-white tracking-tight">$1</strong>')
})

const relatedEntity = computed(() => {
  if (!notification.value?.data) return null

  const data = notification.value.data

  // Determine related entity from notification data
  if (data.project_id || data.project_name) {
    return {
      type: 'Project',
      name: data.project_name || 'Project',
      url: `/projects/${data.project_id}`
    }
  }
  if (data.task_id || data.task_name) {
    return {
      type: 'Task',
      name: data.task_name || 'Task',
      url: `/tasks/${data.task_id}`
    }
  }
  if (data.invoice_id || data.invoice_name) {
    return {
      type: 'Invoice',
      name: data.invoice_name || 'Invoice',
      url: `/invoices/${data.invoice_id}`
    }
  }
  return null
})

// Methods
function getIconComponent(iconName) {
  return iconComponents[iconName] || Info
}

function getAttachmentIcon(type) {
  if (type?.includes('image')) return Image
  if (type?.includes('pdf') || type?.includes('document')) return FileText
  return File
}

function getAttachmentIconClass(type) {
  if (type?.includes('image')) return 'bg-purple-500/10 border border-purple-500/20'
  if (type?.includes('pdf') || type?.includes('document')) return 'bg-orange-500/10 border border-orange-500/20'
  return 'bg-blue-500/10 border border-blue-500/20'
}

function getAttachmentTextColor(type) {
  if (type?.includes('image')) return 'text-purple-400'
  if (type?.includes('pdf') || type?.includes('document')) return 'text-orange-400'
  return 'text-blue-400'
}

async function loadNotification() {
  const notificationId = route.params.id || route.query.id

  if (!notificationId) {
    error.value = 'Notification ID is required'
    loading.value = false
    return
  }

  try {
    const response = await getNotification(notificationId)

    // Map the API response to frontend format
    const apiNotification = response.notification || response.data || response

    const notificationData = apiNotification.data || {}
    const title = notificationData.title || apiNotification.title || 'Notification'
    const message = notificationData.message || apiNotification.message || ''

    const notificationType = notificationData.type || apiNotification.type || 'custom'

    const typeIcons = {
      'task_assigned': { icon: 'CheckCircle2', bgClass: 'bg-emerald-500/10 border border-emerald-500/20', textClass: 'text-emerald-400' },
      'new_message': { icon: 'Info', bgClass: 'bg-blue-500/10 border border-blue-500/20', textClass: 'text-blue-400' },
      'task_status_updated': { icon: 'AlertCircle', bgClass: 'bg-amber-500/10 border border-amber-500/20', textClass: 'text-amber-400' },
      'announcement': { icon: 'Info', bgClass: 'bg-blue-500/10 border border-blue-500/20', textClass: 'text-blue-400' },
      'reminder': { icon: 'Info', bgClass: 'bg-purple-500/10 border border-purple-500/20', textClass: 'text-purple-400' },
      'alert': { icon: 'AlertTriangle', bgClass: 'bg-red-500/10 border border-red-500/20', textClass: 'text-red-400' },
      'project_update': { icon: 'Info', bgClass: 'bg-blue-500/10 border border-blue-500/20', textClass: 'text-blue-400' },
      'custom': { icon: 'Info', bgClass: 'bg-blue-500/10 border border-blue-500/20', textClass: 'text-blue-400' },
    }

    const iconConfig = typeIcons[notificationType] || typeIcons['custom']
    const isRead = apiNotification.read_at !== null || apiNotification.read === true

    notification.value = {
      id: apiNotification.id,
      type: apiNotification.type,
      title,
      message,
      data: notificationData,
      read_at: apiNotification.read_at,
      created_at: apiNotification.created_at,
      unread: !isRead,
      icon: iconConfig.icon,
      bgClass: iconConfig.bgClass,
      textClass: iconConfig.textClass
    }

    // Mark as read if unread
    if (!isRead) {
      await markAsRead(notificationId)
      notification.value.read_at = new Date().toISOString()
      notification.value.unread = false
    }
  } catch (err) {
    error.value = err.response?.data?.message || 'Failed to load notification'
  } finally {
    loading.value = false
  }
}

function goBack() {
  router.back()
}

function toggleStar() {
  isStarred.value = !isStarred.value
}

function shareNotification() {
  if (navigator.share) {
    navigator.share({
      title: notification.value.title,
      text: notification.value.message,
      url: window.location.href
    })
  } else {
    navigator.clipboard.writeText(window.location.href)
    alert('Link copied to clipboard!')
  }
}

function navigateToRelated() {
  if (relatedEntity.value?.url) {
    router.push(relatedEntity.value.url)
  }
}

function downloadAttachment(attachment) {
  // Implement download logic based on your backend
  if (attachment.url) {
    window.open(attachment.url, '_blank')
  }
}

function replyToNotification() {
  // Navigate to related entity or open reply modal
  if (notification.value.data?.task_id) {
    router.push(`/tasks/${notification.value.data.task_id}`)
  } else if (notification.value.data?.project_id) {
    router.push(`/projects/${notification.value.data.project_id}`)
  }
}

async function deleteNotification() {
  if (!confirm('Are you sure you want to delete this notification?')) return

  deleting.value = true
  try {
    await apiDeleteNotification(notification.value.id)
    router.push('/notifications')
  } catch (err) {
    alert('Failed to delete notification')
  } finally {
    deleting.value = false
  }
}

onMounted(() => {
  loadNotification()
})
</script>
